# novi parametar u Symfony kontejneru koji se puni iz .env
parameters:
    app.dictionary_path: '%env(resolve:DICTIONARY_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # automatski registruj sve klase iz src kao servise/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers kao servisi (potrebno za argumente u akcijama, u metodama kontrolera koristimo servise kao argumente)
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # proslijedi putanju u naš DictionaryServic, parametar $dictionaryPath popuni sa %app.dictionary_path%
    App\Service\DictionaryService:
        arguments:
            $dictionaryPath: '%app.dictionary_path%'
